[package]
name = "activities"
version = "0.1.0"
edition = "2024"

[dependencies]
thiserror = "2.0.15"

[dev-dependencies]
strum = { version = "0.27.2", features = ["derive"] }

[build-dependencies]
calamine = "0.30.0"
itertools = "0.14.0"
