[package]
name = "fit-rs"
version = "0.1.0"
edition = "2024"

[dependencies]
thiserror = "2.0.16"

[dev-dependencies]
strum = { version = "0.27.2", features = ["derive"] }

[build-dependencies]
codegen = {path = "../codegen"}
